name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push Docker image
        run: |
          docker build -t ${{ secrets.APPLICATION_NAME }} .
          docker tag ${{ secrets.APPLICATION_NAME }} ${{ steps.login-ecr.outputs.registry }}/${{ secrets.APPLICATION_NAME }}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.APPLICATION_NAME }}:latest

      - name: Create appspec.yml
        run: |
          cat << 'EOF' > appspec.yml
          ${{ secrets.APPSPEC }}
          EOF

      - name: Create start-server.sh
        run: |
          mkdir -p scripts
          cat << 'EOF' > scripts/start-server.sh
          ${{ secrets.START_SERVER_SH }}
          EOF
          chmod +x scripts/start-server.sh

      - name: Package for CodeDeploy
        run: tar -czvf $GITHUB_SHA.tar.gz appspec.yml scripts

      - name: Upload bundle to S3
        run: aws s3 cp --region ${{ secrets.REGION }} $GITHUB_SHA.tar.gz s3://${{ secrets.S3_BUCKET_NAME }}/$GITHUB_SHA.tar.gz

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ secrets.DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=tgz,key=$GITHUB_SHA.tar.gz
